In [55]:
import pandas as pd
import matplotlib.pyplot as plt
from  datetime import datetime
import numpy as np

In [31]:
players = pd.read_csv('../Data/Players With Award Data/players_with_award_voting.csv',index_col=0)
teams = pd.read_csv('../Basketball Reference Stat Scraper/team_stats/pre_1980/all_pre_1980.csv',index_col=0)

test_set = pd.read_csv(
    f'/Users/chaseallbright/Dropbox/NBA/Data/Test Sets/{datetime.now().strftime("%Y")}/{datetime.now().strftime("%Y%m%d")}_player_stats.csv',
    index_col=0)
players = players.append(test_set)

In [32]:
players.loc[players['Player'].str.contains('Chris Paul'),:]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
9986,Chris Paul,PG,20.0,NOK,78.0,78.0,36.0,5.2,12.1,0.430,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10797,Chris Paul,PG,21.0,NOK,64.0,64.0,36.8,6.0,13.6,0.437,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10897,Chris Paul,PG,22.0,NOH,80.0,80.0,37.6,7.9,16.1,0.488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11614,Chris Paul,PG,23.0,NOH,78.0,78.0,38.5,8.1,16.1,0.503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12082,Chris Paul,PG,24.0,NOH,45.0,45.0,38.0,7.0,14.2,0.493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12231,Chris Paul,PG,25.0,NOH,80.0,80.0,36.0,5.4,11.6,0.463,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12665,Chris Paul,PG,26.0,LAC,60.0,60.0,36.4,7.1,14.8,0.478,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13539,Chris Paul,PG,27.0,LAC,70.0,70.0,33.4,5.9,12.2,0.481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14020,Chris Paul,PG,28.0,LAC,62.0,62.0,35.0,6.5,14.0,0.467,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14518,Chris Paul,PG,29.0,LAC,82.0,82.0,34.8,6.9,14.3,0.485,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14686,Chris Paul,PG,30.0,LAC,74.0,74.0,32.7,7.0,15.1,0.462,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15071,Chris Paul,PG,31.0,LAC,61.0,61.0,31.5,6.1,12.9,0.476,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16008,Chris Paul,PG,32.0,HOU,58.0,58.0,31.8,6.3,13.8,0.460,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16239,Chris Paul,PG,33.0,HOU,58.0,58.0,32.0,5.2,12.4,0.419,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17069,Chris Paul,PG,34.0,OKC,70.0,70.0,31.5,6.2,12.7,0.489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17237,Chris Paul,PG,35.0,PHO,65.0,65.0,31.5,6.2,12.5,0.491,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,Chris Paul,PG,36.0,PHO,65.0,65.0,32.9,5.6,11.3,0.493,...,15.6,19.7,5.8,3.6,9.4,0.21,3.1,2.3,5.4,4.0

In [33]:
teams.loc[(teams['Team'].str.contains('Nuggets')) & (teams['Year'] > 2000),:]

,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,2P,...,SOS,SRS,ORtg,DRtg,NRtg,Pace,FTr,3PAr,TS%,Year
18,Denver Nuggets,82.0,241.2,37.6,84.3,0.446,5.1,14.2,0.356,32.5,...,0.64,-1.83,103.7,106.3,-2.6,92.6,0.286,0.210,0.511,2001.0
25,Denver Nuggets,82.0,241.5,36.6,79.8,0.459,5.2,14.3,0.361,31.5,...,0.63,-5.19,101.4,107.8,-6.4,90.4,0.256,0.187,0.495,2002.0
27,Denver Nuggets,82.0,240.6,32.9,74.2,0.443,5.1,13.8,0.370,27.8,...,0.87,-7.41,92.2,101.3,-9.1,91.0,0.283,0.126,0.469,2003.0
10,Denver Nuggets*,82.0,240.6,36.8,81.2,0.453,4.6,12.9,0.356,32.2,...,0.58,1.65,103.9,102.7,1.2,93.3,0.319,0.146,0.517,2004.0
8,Denver Nuggets*,82.0,240.9,36.0,80.6,0.447,5.6,16.4,0.345,30.3,...,0.20,2.23,106.0,103.9,2.1,93.5,0.350,0.142,0.535,2005.0
10,Denver Nuggets*,82.0,243.0,37.4,82.5,0.454,6.5,18.0,0.358,31.0,...,0.13,0.36,105.5,105.2,0.3,93.9,0.347,0.161,0.535,2006.0
9,Denver Nuggets*,82.0,241.2,39.7,86.4,0.460,6.8,19.1,0.353,33.0,...,0.07,1.69,107.6,105.9,1.7,97.4,0.360,0.212,0.548,2007.0
10,Denver Nuggets*,82.0,242.1,40.7,89.1,0.457,7.6,20.9,0.363,33.1,...,0.03,3.74,110.0,106.3,3.7,99.7,0.358,0.228,0.557,2008.0
5,Denver Nuggets*,82.0,240.6,36.2,82.2,0.440,7.3,20.0,0.366,28.8,...,-0.29,3.13,110.4,106.8,3.6,94.3,0.382,0.227,0.563,2009.0
5,Denver Nuggets*,82.0,241.2,37.7,82.5,0.456,6.4,18.3,0.349,31.3,...,0.06,4.15,111.8,107.5,4.3,94.8,0.376,0.227,0.561,2010.0
8,Denver Nuggets*,82.0,240.3,38.5,83.9,0.459,7.0,20.4,0.344,31.4,...,0.05,4.81,112.3,107.3,5.0,95.6,0.367,0.258,0.574,2011.0
10,Denver Nuggets*,66.0,243.0,38.5,84.4,0.456,8.7,22.6,0.383,29.8,...,0.29,3.16,109.2,106.2,3.0,94.2,0.326,0.243,0.556,2012.0
3,Denver Nuggets*,82.0,242.7,38.1,85.7,0.444,8.4,23.1,0.363,29.7,...,0.28,5.37,110.4,105.1,5.3,95.1,0.308,0.217,0.549,2013.0
19,Denver Nuggets,82.0,240.9,39.5,86.4,0.457,7.4,21.0,0.351,32.1,...,0.75,-1.40,106.0,108.2,-2.2,98.1,0.306,0.278,0.536,2014.0
23,Denver Nuggets,82.0,242.4,38.6,84.3,0.458,7.7,22.2,0.346,30.9,...,0.48,-3.07,104.5,108.2,-3.7,96.1,0.278,0.284,0.518,2015.0
20,Denver Nuggets,82.0,241.8,37.7,85.4,0.442,8.0,23.7,0.338,29.7,...,0.29,-2.81,105.6,108.9,-3.3,95.7,0.282,0.277,0.531,2016.0
17,Denver Nuggets,82.0,240.9,41.2,87.7,0.469,10.6,28.8,0.368,30.6,...,0.19,0.70,113.2,112.7,0.5,98.3,0.276,0.329,0.568,2017.0
13,Denver Nuggets,82.0,242.4,40.7,86.6,0.470,11.5,30.9,0.371,29.2,...,0.09,1.57,112.5,111.0,1.5,96.8,0.258,0.357,0.570,2018.0
3,Denver Nuggets*,82.0,240.6,41.9,90.0,0.466,11.0,31.4,0.351,30.9,...,0.24,4.19,113.0,108.9,4.1,97.7,0.232,0.348,0.558,2019.0
5,Denver Nuggets*,73.0,243.1,42.0,88.9,0.473,11.0,30.6,0.359,31.1,...,0.24,2.35,113.1,111.0,2.1,97.1,0.235,0.344,0.567,2020.0
4,Denver Nuggets*,72.0,242.8,43.3,89.2,0.485,12.9,34.2,0.377,30.4,...,-0.11,4.82,117.1,112.1,5.0,97.1,0.219,0.383,0.588,2021.0
8,Denver Nuggets,76.0,241.3,41.3,86.2,0.479,12.8,36.1,0.354,28.6,...,-0.13,2.34,114.0,111.5,2.5,97.6,0.241,0.418,0.586,2022.0

In [38]:
players.loc[(players.Player == 'Nikola Jokić'),['Year','Tm_ORtg','Tm_DRtg']]

       Year  Tm_ORtg  Tm_DRtg
14635  2016    113.2    112.7
15163  2017    112.5    111.0
15602  2018    113.0    108.9
16454  2019      NaN      NaN
16729  2020      NaN      NaN
17638  2021      NaN      NaN
241    2022      NaN      NaN

In [41]:
a = players.columns.to_list()

In [52]:
df_l = []
for i in range(1980,2023):
    df_l.append(pd.read_csv(f'../Basketball Reference Stat Scraper/player_stats/{i}_player_stats.csv',index_col=0))
df = pd.concat(df_l)

df.Player = df.Player.str.strip('*')
df

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Year
0,Kareem Abdul-Jabbar,C,32,LAL,82,0,38.3,10.2,16.9,0.604,...,24.1,9.5,5.3,14.8,0.227,4.8,2.4,7.2,7.3,1980
1,Tom Abernethy,PF,25,GSW,67,0,18.2,2.3,4.7,0.481,...,13.3,1.2,0.8,2.0,0.080,-1.0,-0.2,-1.2,0.2,1980
2,Alvan Adams,C,25,PHO,75,0,28.9,6.2,11.7,0.531,...,21.9,3.1,3.9,7.0,0.155,1.7,1.9,3.6,3.1,1980
3,Tiny Archibald,PG,31,BOS,80,80,35.8,4.8,9.9,0.482,...,17.0,5.9,2.9,8.9,0.148,1.4,-0.3,1.1,2.3,1980
4,Dennis Awtrey,C,31,CHI,26,0,21.5,1.0,2.3,0.450,...,7.9,0.1,0.5,0.6,0.053,-2.3,0.9,-1.4,0.1,1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,Moses Wright,PF,23,LAC,1,0,1.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.443,10.8,13.5,24.3,0.0,2022
510,Trae Young,PG,23,ATL,55,55,34.5,9.4,20.5,0.457,...,35.0,5.9,0.6,6.5,0.164,6.7,-2.1,4.6,3.2,2022
511,Omer Yurtseven,C,23,MIA,44,10,13.9,2.6,4.9,0.540,...,20.0,0.9,1.2,2.0,0.160,-0.8,0.6,-0.2,0.3,2022
512,Cody Zeller,C,29,POR,27,0,13.1,1.9,3.3,0.567,...,16.0,0.9,0.2,1.2,0.158,-0.9,-1.0,-1.9,0.0,2022
513,Ivica Zubac,C,24,LAC,57,57,24.3,3.8,5.8,0.650,...,15.6,3.2,2.1,5.3,0.185,-0.2,1.0,0.8,1.0,2022

In [69]:
# for i in (df.select_dtypes(include=[np.number])).columns:
#     # df.loc[(df['Player'] == 'Nikola Jokić'),['Year',i]].plot()
#     plt.plot('Age',i,data=df.loc[(df['Player'] == 'Nikola Jokić'),['Age',i]])
#     plt.plot('Age',i,data=df.loc[(df['Player'] == 'Chris Paul'),['Age',i]])
#     # plt.plot('Age',i,data=df.loc[(df['Player'] == 'Larry Bird'),['Age',i]])
#     plt.title(i)
#     plt.legend(['Jokic','Paul','Bird'])
#     plt.tight_layout()
#     plt.grid(True)
#     plt.show()

In [72]:
teams.loc[(teams.Year.isin(df.loc[(df['Player'] == 'Nikola Jokić'),'Year'])) & teams.Team.str.contains('Denver'),:]

,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,2P,...,SOS,SRS,ORtg,DRtg,NRtg,Pace,FTr,3PAr,TS%,Year
20,Denver Nuggets,82.0,241.8,37.7,85.4,0.442,8.0,23.7,0.338,29.7,...,0.29,-2.81,105.6,108.9,-3.3,95.7,0.282,0.277,0.531,2016.0
17,Denver Nuggets,82.0,240.9,41.2,87.7,0.469,10.6,28.8,0.368,30.6,...,0.19,0.70,113.2,112.7,0.5,98.3,0.276,0.329,0.568,2017.0
13,Denver Nuggets,82.0,242.4,40.7,86.6,0.470,11.5,30.9,0.371,29.2,...,0.09,1.57,112.5,111.0,1.5,96.8,0.258,0.357,0.570,2018.0
3,Denver Nuggets*,82.0,240.6,41.9,90.0,0.466,11.0,31.4,0.351,30.9,...,0.24,4.19,113.0,108.9,4.1,97.7,0.232,0.348,0.558,2019.0
5,Denver Nuggets*,73.0,243.1,42.0,88.9,0.473,11.0,30.6,0.359,31.1,...,0.24,2.35,113.1,111.0,2.1,97.1,0.235,0.344,0.567,2020.0
4,Denver Nuggets*,72.0,242.8,43.3,89.2,0.485,12.9,34.2,0.377,30.4,...,-0.11,4.82,117.1,112.1,5.0,97.1,0.219,0.383,0.588,2021.0
8,Denver Nuggets,76.0,241.3,41.3,86.2,0.479,12.8,36.1,0.354,28.6,...,-0.13,2.34,114.0,111.5,2.5,97.6,0.241,0.418,0.586,2022.0

In [73]:
teams.loc[(teams.Year.isin(df.loc[(df['Player'] == 'Chris Paul'),'Year'])) & teams.Team.str.contains('Suns'),:]

,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,2P,...,SOS,SRS,ORtg,DRtg,NRtg,Pace,FTr,3PAr,TS%,Year
3,Phoenix Suns*,82.0,243.4,39.5,87.1,0.454,6.3,17.4,0.363,33.3,...,-0.07,5.48,111.5,105.8,5.7,95.8,0.206,0.293,0.568,2006.0
1,Phoenix Suns*,82.0,242.7,39.5,86.4,0.457,6.1,16.9,0.363,33.3,...,-0.03,7.28,113.9,106.4,7.5,95.6,0.267,0.287,0.590,2007.0
6,Phoenix Suns*,82.0,241.2,41.1,90.0,0.456,5.7,16.2,0.353,35.4,...,0.09,5.14,113.3,108.1,5.2,96.7,0.292,0.260,0.590,2008.0
12,Phoenix Suns,82.0,240.9,40.0,85.7,0.467,7.6,19.9,0.383,32.3,...,-0.31,1.62,113.6,111.6,2.0,96.0,0.336,0.216,0.584,2009.0
4,Phoenix Suns*,82.0,240.6,39.5,87.4,0.452,6.8,19.3,0.355,32.6,...,-0.23,4.67,115.3,110.2,5.1,95.3,0.312,0.261,0.585,2010.0
16,Phoenix Suns,82.0,244.0,40.4,85.6,0.472,7.1,19.5,0.367,33.2,...,0.43,-0.46,109.5,110.4,-0.9,94.4,0.283,0.271,0.559,2011.0
17,Phoenix Suns,66.0,240.0,38.0,83.5,0.455,6.0,17.1,0.352,31.9,...,0.53,0.29,106.2,106.5,-0.3,92.6,0.257,0.238,0.536,2012.0
26,Phoenix Suns,82.0,241.5,38.8,82.6,0.470,6.9,17.9,0.388,31.9,...,0.71,-5.75,101.2,108.1,-6.9,93.4,0.234,0.210,0.512,2013.0
11,Phoenix Suns,82.0,240.9,38.0,83.4,0.456,6.8,19.9,0.341,31.2,...,0.39,3.02,109.5,106.7,2.8,95.8,0.293,0.300,0.558,2014.0
16,Phoenix Suns,82.0,242.4,38.4,85.0,0.452,7.7,21.9,0.352,30.7,...,0.52,-0.38,105.3,106.2,-0.9,96.3,0.251,0.291,0.537,2015.0
26,Phoenix Suns,82.0,240.3,37.2,85.6,0.435,9.0,25.8,0.348,28.2,...,0.34,-6.32,102.2,109.0,-6.8,98.5,0.271,0.302,0.526,2016.0
28,Phoenix Suns,82.0,241.8,39.9,88.5,0.450,7.5,22.6,0.332,32.4,...,0.49,-5.14,106.6,112.2,-5.6,100.3,0.297,0.255,0.538,2017.0
29,Phoenix Suns,82.0,240.3,38.5,87.1,0.442,9.3,27.9,0.334,29.1,...,0.57,-8.80,103.5,112.8,-9.3,100.3,0.275,0.320,0.532,2018.0
27,Phoenix Suns,82.0,242.4,40.1,87.4,0.459,9.6,29.3,0.329,30.5,...,0.73,-8.61,105.9,115.1,-9.2,100.5,0.259,0.335,0.552,2019.0
15,Phoenix Suns,73.0,241.0,41.2,88.1,0.468,11.4,31.8,0.358,29.8,...,0.35,0.56,111.7,111.4,0.3,101.3,0.271,0.361,0.576,2020.0
1,Phoenix Suns*,72.0,242.8,43.3,88.3,0.490,13.1,34.6,0.378,30.3,...,-0.15,5.67,117.2,111.3,5.9,97.2,0.212,0.392,0.597,2021.0
0,Phoenix Suns,75.0,240.7,43.7,89.6,0.488,11.7,31.6,0.370,32.0,...,-0.62,7.83,115.6,107.1,8.5,99.5,0.226,0.353,0.586,2022.0